Models/Cursos_db.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace apiGestores.Models
{
    public class Cursos_db
    {
        [Key]
        public int id { get; set; }

        [Required]
        [Display(Name = "Nombre del curso")]
        public String name { get; set; }

        [Display(Name = "Lanzamiento")]
        public int launch { get; set; }

        [Display(Name = "Desarrolador")]
        public String developer { get; set; }

    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace apiGestores.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace apiGestores.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace apiGestores.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/listCourses/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using apiGestores.Context;
using apiGestores.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace apiGestores.Pages.listCourses
{
    public class CreateModel : PageModel
    {
        private readonly AppDbContext _db;
        public CreateModel(AppDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public Cursos_db Curso { get; set; }

        [TempData]
        public string Mensaje { get; set; }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _db.Add(Curso);
            await _db.SaveChangesAsync();

            Mensaje = "Curso creado correctamente";

            return RedirectToPage("Index");
        }
    }
}

Pages/listCourses/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using apiGestores.Context;
using apiGestores.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace apiGestores.Pages.listCourses
{
    public class EditModel : PageModel
    {
        private readonly AppDbContext _db;
        public EditModel(AppDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public Cursos_db Curso { get; set; }

        [TempData]
        public string Mensaje { get; set; }

        public async Task OnGet(int id)
        {
            Curso = await _db.cursos_db.FindAsync(id);
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                var cursoDesdeDb = await _db.cursos_db.FindAsync(Curso.id);
                cursoDesdeDb.name = Curso.name;
                cursoDesdeDb.launch = Curso.launch;
                cursoDesdeDb.developer = Curso.developer;

                await _db.SaveChangesAsync();

                Mensaje = "Curso actualizado correctamente";

                return RedirectToPage("Index");
            }

            return RedirectToPage();
        }
    }
}

Pages/listCourses/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using apiGestores.Context;
using apiGestores.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace apiGestores.Pages.listCourses
{
    public class IndexModel : PageModel
    {
        private readonly AppDbContext _db;
        public IndexModel(AppDbContext db)
        {
            _db = db;
        }

        public IEnumerable<Cursos_db> Cursos { get; set; }

        [TempData]
        public string Mensaje { get; set; }

        public async Task OnGet()
        {
            Cursos = await _db.cursos_db.ToListAsync();
        }

        public async Task<IActionResult> OnPostDelete(int id)
        {
            var curso = await _db.cursos_db.FindAsync(id);

            if (curso == null)
            {
                return NotFound();
            }

            _db.cursos_db.Remove(curso);
            await _db.SaveChangesAsync();

            Mensaje = "Curso borrado correctamente";

            return RedirectToPage("index");
        }
    }
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - apiGestores</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-light" asp-area="" asp-page="/Index">apiCursos</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-page="/listCourses/Index">Cursos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - apiGestores - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Pages/listCourses/Create.cshtml
@page
@model apiGestores.Pages.listCourses.CreateModel
@{
    ViewData["Title"] = "Create";
}

<br />
<h2 class="text-info">Crear nuevo curso</h2>
<div class="border">
    <form method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="container" style="padding:30px;">
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Curso.name">Nombre del curso</label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Curso.name" class="form-control" />
                    </div>
                    <span asp-validation-for="Curso.name" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Curso.launch">Lanzamiento</label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Curso.launch" class="form-control" />
                    </div>
                    <span asp-validation-for="Curso.launch" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Curso.developer"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Curso.developer" class="form-control" />
                    </div>
                    <span asp-validation-for="Curso.developer" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2 offset-sm-2">
                        <input type="submit" value="Crear" class="btn btn-primary form-control" />
                    </div>
                    <div class="col-sm-2">
                        <a asp-page="Index" class="btn btn-success form-control">Volver a lista</a>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

@section Scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/listCourses/Edit.cshtml
@page
@model apiGestores.Pages.listCourses.EditModel
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>
<br />
<h2 class="text-info">Edit curso</h2>
<div class="border">
    <form method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Curso.id" />
        <div class="container" style="padding:30px;">
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Curso.name">Nombre del curso</label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Curso.name" class="form-control" />
                    </div>
                    <span asp-validation-for="Curso.name" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Curso.launch">Lanzamiento</label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Curso.launch" class="form-control" />
                    </div>
                    <span asp-validation-for="Curso.launch" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Curso.developer"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Curso.developer" class="form-control" />
                    </div>
                    <span asp-validation-for="Curso.developer" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2 offset-sm-2">
                        <input type="submit" value="Actualizar" class="btn btn-primary form-control" />
                    </div>
                    <div class="col-sm-2">
                        <a asp-page="Index" class="btn btn-success form-control">Volver a lista</a>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

@section Scripts{ 
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/listCourses/Index.cshtml
@page
@model apiGestores.Pages.listCourses.IndexModel
@{
    ViewData["Title"] = "Index";
}
<br/>
<div class="container row">
    <div class="col-6">
        <h2 class="text-info">Lista de Cursos</h2>
    </div>
    <div class="col-6 text-right">
        <a asp-page="Create" class="btn btn-primary">Crear nuevo curso</a>
    </div>
</div>

@if (Model.Mensaje != null)
{
    <div class="alert alert-info alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="close">
            <span aria-hidden="true">&times;</span>
        </button>
        @Model.Mensaje
    </div>
}

<form method="post">
    @if (Model.Cursos.Count() > 0)
    {
        <br /><br />
        <table class="table table-striped border">
            <tr class="table-secondary">
                <th>
                    @Html.DisplayFor(m => m.Cursos.FirstOrDefault().name)
                </th>
                <th>
                    @Html.DisplayFor(m => m.Cursos.FirstOrDefault().launch)
                </th>
                <th>
                    @Html.DisplayFor(m => m.Cursos.FirstOrDefault().developer)
                </th>
                <th>
                    Acciones
                </th>
            </tr>
            @foreach (var item in Model.Cursos)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(m => item.name)
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.launch)
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.developer)
                    </td>
                    <td>
                        <button asp-page-handler="Delete" asp-route-id="@item.id" onclick="return confirm('¿Esta seguro de que desea borralo?')" class="btn btn-danger btn-sm">Borrar</button>
                        <a asp-route-id="@item.id" asp-page="Edit" class="btn btn-success btn-sm">Editar</a>
                    </td>
                </tr>
            }

        </table>
    }
    else
    {
        <p>No hay cursos disponibles</p>
    }
</form>